package runnerimages

import (
	"fmt"
	"strings"
)

// SetupScript renders the bash script executed inside the bake VM (from
// the mounted seed share, as root) that lays out /imagegeneration exactly
// like the upstream Packer file provisioners do and then runs the plan's
// steps in order.
//
// Failure policy: one broken installer should not throw away hours of
// baking, so non-critical script failures are recorded and reported while
// the bake continues; scripts in criticalScripts abort the bake.
func (p Plan) SetupScript() string {
	var b strings.Builder
	b.WriteString(`#!/bin/bash
# generated by gh-runnerd from ` + Repo + `@` + p.Ref + ` (` + string(p.Flavor) + `)
set -uo pipefail
SEED=/mnt/gh-runnerd-seed
ROOT="$SEED/runner-images"
SRC="$ROOT/images/ubuntu"
IMG=/imagegeneration
LOGS=$IMG/logs
PROGRESS="$SEED/PARITY_PROGRESS"
FAILED_MARKER="$SEED/PARITY_FAILED"
rm -f "$FAILED_MARKER" "$PROGRESS"

# The layout the upstream Packer file provisioners create on Azure VMs.
mkdir -p "$IMG" "$LOGS"
chmod 777 "$IMG"
cp -a "$SRC/scripts/helpers" "$IMG/helpers"
cp -a "$SRC/scripts/build" "$IMG/installers"
[ -d "$SRC/scripts/tests" ] && cp -a "$SRC/scripts/tests" "$IMG/tests"
if [ -d "$SRC/scripts/docs-gen" ]; then
  cp -a "$SRC/scripts/docs-gen" "$IMG/SoftwareReport"
  [ -d "$ROOT/helpers/software-report-base" ] && cp -a "$ROOT/helpers/software-report-base" "$IMG/SoftwareReport/"
fi
[ -d "$SRC/assets/post-gen" ] && cp -a "$SRC/assets/post-gen" "$IMG/post-generation"
`)
	fmt.Fprintf(&b, "cp \"$SRC/toolsets/%s\" \"$IMG/installers/toolset.json\"\n", p.Toolset)
	b.WriteString(`chmod -R a+rx "$IMG/helpers" "$IMG/installers"

# The upstream scripts sed Azure's agent config in place; give them a
# file to edit since no waagent exists here.
if [ ! -f /etc/waagent.conf ]; then
  printf 'ResourceDisk.Format=n\nResourceDisk.EnableSwap=n\nResourceDisk.SwapSizeMB=0\n' > /etc/waagent.conf
fi

export DEBIAN_FRONTEND=noninteractive
FAILED_STEPS=""
CRITICAL_FAILED=""

run_step() {
  local idx=$1 total=$2 kind=$3 critical=$4 name=$5
  shift 5
  local path="$IMG/installers/$name"
  local log="$LOGS/$(printf '%03d' "$idx")-$name.log"
  echo "[$idx/$total] $name" >> "$PROGRESS"
  echo ">>> [$idx/$total] $name"
  local rc=0
  if [ "$kind" = pwsh ]; then
    env "$@" pwsh -f "$path" > "$log" 2>&1 || rc=$?
  else
    env "$@" "$path" > "$log" 2>&1 || rc=$?
  fi
  if [ "$rc" -ne 0 ]; then
    echo "[$idx/$total] $name FAILED rc=$rc" >> "$PROGRESS"
    echo "!!! $name failed (rc=$rc), last lines:"
    tail -n 25 "$log" || true
    FAILED_STEPS="$FAILED_STEPS $name"
    if [ "$critical" = yes ]; then
      CRITICAL_FAILED="$CRITICAL_FAILED $name"
    fi
  fi
}

`)
	total := p.ScriptCount()
	idx := 0
	for _, step := range p.Steps {
		kind := "shell"
		if step.Pwsh {
			kind = "pwsh"
		}
		for _, script := range step.Scripts {
			idx++
			critical := "no"
			if criticalScripts[script] {
				critical = "yes"
			}
			fmt.Fprintf(&b, "run_step %d %d %s %s %s", idx, total, kind, critical, shellQuote(script))
			for _, kv := range step.Env {
				b.WriteString(" " + shellQuote(kv))
			}
			b.WriteString("\n")
			if script == "configure-environment.sh" && p.Flavor == FlavorEssential {
				// invoke_tests runs upstream Pester suites; essential skips
				// the PowerShell modules that provide them, so neuter it
				// right after configure-environment installs the symlink.
				b.WriteString(`rm -f /usr/local/bin/invoke_tests
printf '#!/bin/sh\nexit 0\n' > /usr/local/bin/invoke_tests
chmod +x /usr/local/bin/invoke_tests
`)
			}
		}
	}

	b.WriteString(`
# GitHub runs these at the first boot of every hosted VM; values are
# static for our single-user image, so run them once here.
if [ -d /opt/post-generation ]; then
  for s in /opt/post-generation/*.sh; do
    [ -e "$s" ] || continue
    bash "$s" >> "$LOGS/post-generation.log" 2>&1 || true
  done
fi

`)
	fmt.Fprintf(&b, "REPORT=/etc/gh-runnerd-image\n{\n  echo \"source=%s@%s\"\n  echo \"flavor=%s\"\n  echo \"family=%s\"\n", Repo, p.Ref, p.Flavor, p.Family)
	b.WriteString(`  echo "failed_scripts=${FAILED_STEPS# }"
} > "$REPORT"

if [ -n "$FAILED_STEPS" ]; then
  echo "failed:${FAILED_STEPS# }" > "$FAILED_MARKER"
fi
if [ -n "$CRITICAL_FAILED" ]; then
  echo "critical provisioning scripts failed:$CRITICAL_FAILED"
  exit 1
fi
echo "hosted software setup done" >> "$PROGRESS"
exit 0
`)
	return b.String()
}

// shellQuote single-quotes a value for safe interpolation into bash.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
